// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fb82890770
// Version Date: 2020-10-25T05:29:35Z

package handlers

import (
	"github.com/Reasno/kitty/app/svc"
	pb "github.com/Reasno/kitty/proto"
)

func NewEndpoints(service pb.AppServer) svc.Endpoints {
	// Business domain.

	// Wrap Service with middlewares. See handlers/middlewares.go
	service = WrapService(service)

	// Endpoint domain.
	var (
		loginEndpoint   = svc.MakeLoginEndpoint(service)
		getcodeEndpoint = svc.MakeGetCodeEndpoint(service)
	)

	endpoints := svc.Endpoints{
		LoginEndpoint:   loginEndpoint,
		GetCodeEndpoint: getcodeEndpoint,
	}

	// Wrap selected Endpoints with middlewares. See handlers/middlewares.go
	endpoints = WrapEndpoints(endpoints)

	return endpoints
}
