// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package module

import (
	"github.com/go-kit/kit/log"
	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"glab.tagtic.cn/ad_gains/kitty/app/handlers"
	"glab.tagtic.cn/ad_gains/kitty/app/repository"
	"glab.tagtic.cn/ad_gains/kitty/pkg/config"
	"glab.tagtic.cn/ad_gains/kitty/pkg/contract"
	"glab.tagtic.cn/ad_gains/kitty/pkg/khttp"
	"glab.tagtic.cn/ad_gains/kitty/pkg/otredis"
	"glab.tagtic.cn/ad_gains/kitty/pkg/ots3"
	"glab.tagtic.cn/ad_gains/kitty/pkg/sms"
	"glab.tagtic.cn/ad_gains/kitty/pkg/wechat"
)

// Injectors from wire.go:

func injectModule(reader contract.ConfigReader, logger log.Logger) (*Module, func(), error) {
	dialector, err := provideDialector(reader)
	if err != nil {
		return nil, nil, err
	}
	gormConfig := provideGormConfig(logger, reader)
	jaegerLogger := provideJaegerLogAdapter(logger)
	tracer, cleanup, err := provideOpentracing(jaegerLogger, reader)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := provideGormDB(dialector, gormConfig, tracer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	securityConfig := provideSecurityConfig(reader)
	appName := config.ProvideAppName(reader)
	env := config.ProvideEnv(reader)
	histogram := provideHistogramMetrics(appName, env)
	moduleOverallMiddleware := provideEndpointsMiddleware(logger, securityConfig, histogram, tracer, env, appName)
	kafkaProducerFactory, cleanup3 := provideKafkaProducerFactory(reader, logger, tracer)
	moduleUserBus := provideUserBus(kafkaProducerFactory, reader)
	moduleEventBus := provideEventBus(kafkaProducerFactory, reader)
	userRepo := repository.NewUserRepo(db)
	universalClient, cleanup4 := provideRedis(logger, reader, tracer)
	keyManager := provideKeyManager(appName, env)
	codeRepo := repository.NewCodeRepo(universalClient, keyManager, env)
	extraRepo := repository.NewExtraRepo(universalClient, keyManager)
	client := provideHttpClient(tracer)
	transportConfig := provideSmsConfig(client, reader)
	transport := sms.NewTransport(transportConfig)
	wechatConfig := provideWechatConfig(reader, client)
	wechatTransport := wechat.NewTransport(wechatConfig)
	manager := provideUploadManager(tracer, reader, client)
	fileRepo := repository.NewFileRepo(manager, client)
	appService := handlers.NewAppService(reader, logger, userRepo, codeRepo, extraRepo, transport, wechatTransport, manager, fileRepo)
	monitoredAppService := handlers.NewMonitoredAppService(moduleUserBus, moduleEventBus, appService)
	module := provideModule(db, tracer, logger, moduleOverallMiddleware, monitoredAppService, appName)
	return module, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var DbSet = wire.NewSet(
	provideDialector,
	provideGormConfig,
	provideGormDB,
)

var OpenTracingSet = wire.NewSet(
	provideJaegerLogAdapter,
	provideOpentracing,
)

var AppServerSet = wire.NewSet(
	provideSmsConfig,
	DbSet,
	OpenTracingSet,
	provideKeyManager,
	provideHttpClient,
	provideUploadManager,
	provideRedis,
	provideWechatConfig, wechat.NewTransport, sms.NewTransport, repository.NewUserRepo, repository.NewCodeRepo, repository.NewFileRepo, repository.NewExtraRepo, config.ProvideAppName, config.ProvideEnv, handlers.NewAppService, wire.Bind(new(redis.Cmdable), new(redis.UniversalClient)), wire.Bind(new(contract.SmsSender), new(*sms.Transport)), wire.Bind(new(contract.Keyer), new(otredis.KeyManager)), wire.Bind(new(contract.Uploader), new(*ots3.Manager)), wire.Bind(new(contract.HttpDoer), new(*khttp.Client)), wire.Bind(new(contract.Env), new(config.Env)), wire.Bind(new(contract.AppName), new(config.AppName)), wire.Bind(new(handlers.UserRepository), new(*repository.UserRepo)), wire.Bind(new(handlers.CodeRepository), new(*repository.CodeRepo)), wire.Bind(new(handlers.FileRepository), new(*repository.FileRepo)), wire.Bind(new(handlers.ExtraRepository), new(*repository.ExtraRepo)),
)
