// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SmsSender is an autogenerated mock type for the SmsSender type
type SmsSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, mobile, content
func (_m *SmsSender) Send(ctx context.Context, mobile string, content string) error {
	ret := _m.Called(ctx, mobile, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, mobile, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
