// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5626408a2e
// Version Date: 2020-10-16T10:00:30Z

package main

import (
	"flag"

	// This Service
	"github.com/Reasno/kitty/app/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(server.DefaultConfig)
}
