// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dmp.proto

package kitty

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _dmp_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on DmpReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *DmpReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for PackageName

	// no validation rules for Suuid

	// no validation rules for Channel

	return nil
}

// DmpReqValidationError is the validation error returned by DmpReq.Validate if
// the designated constraints aren't met.
type DmpReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DmpReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DmpReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DmpReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DmpReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DmpReqValidationError) ErrorName() string { return "DmpReqValidationError" }

// Error satisfies the builtin error interface
func (e DmpReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDmpReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DmpReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DmpReqValidationError{}

// Validate checks the field values on DmpResp with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *DmpResp) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for AdClick

	// no validation rules for AdComplete

	// no validation rules for AdDisplay

	// no validation rules for AdCtrDev

	// no validation rules for Register

	// no validation rules for Score

	// no validation rules for ScoreTotal

	// no validation rules for BlackType

	// no validation rules for Ext

	return nil
}

// DmpRespValidationError is the validation error returned by DmpResp.Validate
// if the designated constraints aren't met.
type DmpRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DmpRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DmpRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DmpRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DmpRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DmpRespValidationError) ErrorName() string { return "DmpRespValidationError" }

// Error satisfies the builtin error interface
func (e DmpRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDmpResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DmpRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DmpRespValidationError{}
